/* =========================================================
   Гласник — библиография (генерирано от Zotero, група „Glasnik“)
   ---------------------------------------------------------
   Този файл е създаден автоматично от CSV експорт на Zotero.
   За промени: редактирайте записа в Zotero, експортирайте отново
   и заменете файла. Може и да го редактирате на ръка.

   topic  — „Банат“, „Бесарабия“ или „Българи католици“
   kind   — „Извор“ (издания до 1870 г.) или „Изследване“
   places — общности от data.js, с които записът е свързан
   ========================================================= */

const sources = [
  {
    "id": "ZPMRUWVG",
    "type": "Книга",
    "year": 1844,
    "authors": [
      "Jakovsky, Jacobus"
    ],
    "editors": [],
    "translators": [],
    "title": "Alphabetum Bulgaricum sive cyrillianum nunc primum editum catholicis thraciae bulgaris",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Propaganda fide",
    "place": "Romae",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Извор"
  },
  {
    "id": "A9I9PSRK",
    "type": "Книга",
    "year": 1844,
    "authors": [
      "Jakovsky, Jacobus",
      "Arabagisky, Petrus"
    ],
    "editors": [],
    "translators": [],
    "title": "Nauka kristianska za kristianete od Filibelskata darxiava",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Propaganda fide",
    "place": "U Rim",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Извор"
  },
  {
    "id": "3QT7SJA7",
    "type": "Книга",
    "year": 1851,
    "authors": [
      "Berecz, Imre"
    ],
    "editors": [],
    "translators": [],
    "title": "Mananchija kathekismus za katholicsanske paulichane",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Stampal ij Josu Beichel",
    "place": "Temisvar",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [
      "Тимишоара"
    ],
    "kind": "Извор"
  },
  {
    "id": "VJJEC76A",
    "type": "Книга",
    "year": 1866,
    "authors": [
      "Jakovsky, Jacobus"
    ],
    "editors": [],
    "translators": [],
    "title": "Knigice od molitvi, kojeto na svetlost dadi Prisvetli Gospodin Karlo Pooten, Biskup od Maronia i Apostolski nemestnik od Antivari",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Peciátniza na sv. ob. Prapagándsco",
    "place": "U Rim",
    "isbn": "",
    "doi": "",
    "url": "http://dspace.cl.bas.bg/xmlui/handle/nls/807",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Извор"
  },
  {
    "id": "HNV7WQNA",
    "type": "Книга",
    "year": 1866,
    "authors": [
      "Rill, Józu"
    ],
    "editors": [],
    "translators": [],
    "title": "Bâlgàrskutu právupísanji",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "G. Emich",
    "place": "Pešta",
    "isbn": "",
    "doi": "",
    "url": "https://commons.wikimedia.org/wiki/File:B%C3%A2lg%C3%A0rskutu_pr%C3%A1vup%C3%ADsanji_(The_Bulgarian_Orthography).pdf",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Извор"
  },
  {
    "id": "8C7ZWREL",
    "type": "Статия",
    "year": 1896,
    "authors": [
      "Милетич, Любомир"
    ],
    "editors": [],
    "translators": [],
    "title": "На гости у банатските българи",
    "translatedTitle": "",
    "container": "Български преглед",
    "volume": "3",
    "issue": "3",
    "pages": "40–57",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "VFYTI4R5",
    "type": "Статия",
    "year": 1897,
    "authors": [
      "Милетич, Любомир"
    ],
    "editors": [],
    "translators": [],
    "title": "Заселение на католишките българи в Седмиградско и Банат",
    "translatedTitle": "",
    "container": "Сборник за народни умотворения, наука и книжнина",
    "volume": "14",
    "issue": "",
    "pages": "284–543",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "SGAYD5F3",
    "type": "Статия",
    "year": 1900,
    "authors": [
      "Милетич, Любомир"
    ],
    "editors": [],
    "translators": [],
    "title": "Книжнината и езикът на банатските българи",
    "translatedTitle": "",
    "container": "Сборник за народни умотворения, наука и книжнина",
    "volume": "16–17",
    "issue": "",
    "pages": "339–482",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "46QHE9MJ",
    "type": "Статия",
    "year": 1903,
    "authors": [
      "Милетич, Любомир"
    ],
    "editors": [],
    "translators": [],
    "title": "Нашите павликяни",
    "translatedTitle": "",
    "container": "Сборник за народни умотворения, наука и книжнина",
    "volume": "19",
    "issue": "",
    "pages": "1–368",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "58H94N2H",
    "type": "Книга",
    "year": 1914,
    "authors": [
      "Милев, Никола И."
    ],
    "editors": [],
    "translators": [],
    "title": "Католишката пропаганда в България през ХVII век",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Придворна печатница",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "FMPMR4YT",
    "type": "Статия",
    "year": 1929,
    "authors": [
      "Цонев, Беньо"
    ],
    "editors": [],
    "translators": [],
    "title": "Един павликянски ръкопис от втората половина на ХVІІІ век",
    "translatedTitle": "",
    "container": "Годишник на Софийския университет. Историко-филологически факултет",
    "volume": "25",
    "issue": "6",
    "pages": "1–64",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "https://digital.libsu.uni-sofia.bg/bg/v/59508",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "SINQUD3H",
    "type": "Глава от книга",
    "year": 1939,
    "authors": [
      "Гиев, Георги"
    ],
    "editors": [],
    "translators": [],
    "title": "Кратки биографии на мисионерите капуцини чужденци, свещенодействали и работили в Софийско-Пловдивската епархия",
    "translatedTitle": "",
    "container": "Календар „Св. Кирил и Методий“ за 1939",
    "volume": "",
    "issue": "",
    "pages": "67–80",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "BGPVKTKC",
    "type": "Книга",
    "year": 1968,
    "authors": [
      "Стойков, Стойко"
    ],
    "editors": [],
    "translators": [],
    "title": "Лексиката на банатския говор",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "БАН",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "9IL49QNA",
    "type": "Книга",
    "year": 1979,
    "authors": [
      "Райков, Божидар"
    ],
    "editors": [],
    "translators": [],
    "title": "Абагар на Филип Станиславов, Рим 1651.",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Народна просвета",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "MC9IW4Z9",
    "type": "Глава от книга",
    "year": 1980,
    "authors": [
      "Динеков, Петър"
    ],
    "editors": [
      "Божилов, Иван",
      "Гюзелев, Васил"
    ],
    "translators": [],
    "title": "Католишката книжнина в историята на българската литература (методологически въпроси)",
    "translatedTitle": "",
    "container": "Българско Средновековие. Българо-съветски сборник в чест 70-годишнината на проф. Ив. Дуйчев.",
    "volume": "",
    "issue": "",
    "pages": "287–291",
    "publisher": "Наука и изкуство",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "CKN7IC2L",
    "type": "Статия",
    "year": 1981,
    "authors": [
      "Станчев, Красимир"
    ],
    "editors": [],
    "translators": [],
    "title": "Литературата на българите католици през XVII и XVIII век и преходът от Средновековие към Възраждане",
    "translatedTitle": "",
    "container": "Литературна мисъл",
    "volume": "",
    "issue": "3",
    "pages": "3–11",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [
      "17–18 век",
      "книжнина – католическа"
    ],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "CM7HLV59",
    "type": "Статия",
    "year": 1981,
    "authors": [
      "Телбизов, Карол"
    ],
    "editors": [],
    "translators": [],
    "title": "Чипровската книжовна школа. Обзорен библиографски опи",
    "translatedTitle": "",
    "container": "Литературна мисъл",
    "volume": "",
    "issue": "6",
    "pages": "121–138",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [
      "Чипровци",
      "библиография",
      "книжовна школа"
    ],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "E27ILCMB",
    "type": "Статия",
    "year": 1982,
    "authors": [
      "Минчева, Ангелина"
    ],
    "editors": [],
    "translators": [],
    "title": "Езиковата ситуация в българските земи през XVIII в. и Паисиевата „История славеноболгарская“",
    "translatedTitle": "",
    "container": "Palaeobulgarica / Старобългаристика",
    "volume": "6",
    "issue": "4",
    "pages": "37–43",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "CVM3J8NP",
    "type": "Книга",
    "year": 1987,
    "authors": [
      "Милетич, Любомир"
    ],
    "editors": [],
    "translators": [],
    "title": "Изследвания за българите в Седмиградско и Банат",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Наука и изкуство",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "RZYUJTRG",
    "type": "Книга",
    "year": 1988,
    "authors": [
      "Станимиров, Свилен"
    ],
    "editors": [],
    "translators": [],
    "title": "Политическата дейност на българите католици през 30-те-70-те години на XVII век",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Наука и изкуство",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [
      "17 век",
      "българи католици",
      "политика"
    ],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "KP4XIRFQ",
    "type": "Книга",
    "year": 1991,
    "authors": [
      "Йовков, Милчо"
    ],
    "editors": [],
    "translators": [],
    "title": "Павликяни и павликянски селища в българските земи XV-XVIII век",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Университетско издателство „Св. Климент Охридски“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "JZJ2EM25",
    "type": "Глава от книга",
    "year": 1999,
    "authors": [
      "Заимова, Рая",
      "Генов, Румен"
    ],
    "editors": [],
    "translators": [],
    "title": "Католическите календари и покръстването на българите",
    "translatedTitle": "",
    "container": "Етноси, култури и политика в Югоизточна Европа : юбилеен сборник с материали от научна конференция, посветена на 70-годишнината на проф. Цветана Георгиева",
    "volume": "",
    "issue": "",
    "pages": "194–201",
    "publisher": "Нов български университет",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "RTI4GMAG",
    "type": "Книга",
    "year": 2004,
    "authors": [
      "Walczak-Mikołajczakowa, Mariola"
    ],
    "editors": [],
    "translators": [],
    "title": "Piśmiennictwo katolickie w Bułgarii",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Uniw. im. Adama Mickiewicza",
    "place": "Poznań",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "CTND9Y8Q",
    "type": "Статия",
    "year": 2006,
    "authors": [
      "Jerkov, Janja."
    ],
    "editors": [],
    "translators": [],
    "title": "La relazioni delle visite apostoliche fra I pauliciani bulgari del XVIII secolo",
    "translatedTitle": "",
    "container": "Ricerche Slavistiche",
    "volume": "50",
    "issue": "4",
    "pages": "85–204",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "UGIPR8QQ",
    "type": "Глава от книга",
    "year": 2009,
    "authors": [
      "Димитрова, Маргарет"
    ],
    "editors": [
      "Милтенова, Анисава"
    ],
    "translators": [],
    "title": "Книжнината на българите католици",
    "translatedTitle": "",
    "container": "История на българската средновековна литература",
    "volume": "",
    "issue": "",
    "pages": "744–752",
    "publisher": "Изток-Запад",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "67EAGFA9",
    "type": "Статия",
    "year": 2014,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [],
    "translators": [],
    "title": "Книжовен език на народна основа ли е павликянската книжнина от втората половина на XVIII в.",
    "translatedTitle": "",
    "container": "Palaeobulgarica / Старобългаристика",
    "volume": "38",
    "issue": "4",
    "pages": "68–79",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "Despite numerous studies on the Bulgarian literary language from the times before the Bulgarian renascence there still exist manuscripts that have not yet been analyzed properly, viz. samples of Paulician literature from the end of the 18th century. In addition to being a valuable source for Bulgarian historical grammar and dialectology they reflect the typical trend of the period towards democratization of the Bulgarian literary language. In previous research examples of the literary language on a vernacular base (KENO) (Demina 1971:121) were only taken from the Damaskini. The aim of my research is to enlarge the corpus of texts assumed to represent KENO and to include in it the Paulician literature from the second half of the 18th century.",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "RQ5ZSG8I",
    "type": "Статия",
    "year": 2016,
    "authors": [
      "Цибранска-Костова, Марияна",
      "Абаджиева, Магдалена"
    ],
    "editors": [],
    "translators": [],
    "title": "За лексиката с чужд произход в католическата литература (литература на българите католици) XVII–XVIII век (по материал на Абагара на Филип Станиславов и сборник № 778 НБКМ на Петър Ковачев Царски)",
    "translatedTitle": "",
    "container": "Известия на Института за български език",
    "volume": "29",
    "issue": "",
    "pages": "7–47",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [
      "17–18 век",
      "Абагар",
      "НБКМ 778",
      "Петър Ковачев Царски",
      "Филип Станиславов",
      "българи католици",
      "лексика"
    ],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "BPSL3NAS",
    "type": "Дисертация",
    "year": 2017,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [],
    "translators": [],
    "title": "Павликянската книжнина от XVIII век в историята на българския език",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Институт за български език, БАН",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "IEWGRQ4C",
    "type": "Глава от книга",
    "year": 2017,
    "authors": [
      "Aleksova, Vasilka",
      "Zamfira, Mihail"
    ],
    "editors": [],
    "translators": [],
    "title": "Un manuscris inedit în limba bulgară cu litere latine (1779)",
    "translatedTitle": "",
    "container": "Istorie, cultură și politică ăn Sud-estul Europei. (Două colocvii internaționale)",
    "volume": "",
    "issue": "",
    "pages": "41–53",
    "publisher": "Istros",
    "place": "Brăila",
    "isbn": "",
    "doi": "",
    "url": "https://acadsudest.ro/sites/default/files/BSCSE/7%202017%2C%20V%C4%83t%C4%83%C8%99escu%2C%20Iordan..pdf",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "9D7RFI77",
    "type": "Статия",
    "year": 2018,
    "authors": [
      "Греъм, Флорънс"
    ],
    "editors": [],
    "translators": [],
    "title": "Анализ на правописа на три български павликянски паметника от XVIII в., написани на латиница",
    "translatedTitle": "",
    "container": "Език и литература",
    "volume": "",
    "issue": "3–4",
    "pages": "113–122",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "HU4GEAJR",
    "type": "Статия",
    "year": 2019,
    "authors": [
      "Абаджиева, Магдалена",
      "Цибранска-Костова, Марияна"
    ],
    "editors": [
      "Мичева, Ваня",
      "Благоева, Диана",
      "Колковска, Сия",
      "Александрова, Татяна",
      "Дейкова, Христина"
    ],
    "translators": [],
    "title": "Християнската лексика на Славянския юг между православие и католицизъм: лексемата рѧдовьникъ",
    "translatedTitle": "",
    "container": "Доклади от Международната годишна конференция на Института за български език „Проф. Любомир Андрейчин“ (София, 14–15 май 2019 г.)",
    "volume": "50",
    "issue": "",
    "pages": "138–145",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [
      "Banat",
      "Banat Bulgarians",
      "foreign linguistic influences on the Bulgarian language",
      "literature of Bulgarian Catholics"
    ],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "4NMSP2AD",
    "type": "Книга",
    "year": 2020,
    "authors": [],
    "editors": [
      "Радев, Иван"
    ],
    "translators": [
      "Кабакчиев, Кирил"
    ],
    "title": "Абагар на Филип Станиславов. Рим 1651",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Абагар",
    "place": "Велико Търново",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "4RGY2SIL",
    "type": "Книга",
    "year": 2020,
    "authors": [
      "Илиева, Лилия"
    ],
    "editors": [],
    "translators": [],
    "title": "Петър Богдан. Двете смърти на човека: поема: Рим, 1638 г.: текст и изследване",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Университетско издателство „Неофит Рилски“",
    "place": "Благоевград",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "GAUG4FFI",
    "type": "Глава от книга",
    "year": 2020,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [
      "Коева, Светла"
    ],
    "translators": [],
    "title": "Нови данни за книжнината на българите католици през XIX век",
    "translatedTitle": "",
    "container": "Доклади от Международната годишна конференция на Института за български език „Проф. Любомир Андрейчин“",
    "volume": "1",
    "issue": "",
    "pages": "250–254",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "P9HAJQYN",
    "type": "Книга",
    "year": 2020,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [],
    "translators": [],
    "title": "Ръкописният българско-италиански речник на отец Маурицио от 1845 г.",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Симолини",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "FW42AS24",
    "type": "Книга",
    "year": 2020,
    "authors": [
      "Graham, Florence Lydia"
    ],
    "editors": [],
    "translators": [],
    "title": "Turkisms in South Slavonic Literature. Turkish Loanwords in Seventeenthand Eighteenth-Century Bosnian and Bulgarian Franciscan Sources",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Oxford University Press",
    "place": "Oxford",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "KAQCLZAB",
    "type": "Книга",
    "year": 2021,
    "authors": [
      "Младенова, Маринела"
    ],
    "editors": [],
    "translators": [],
    "title": "Банатският български книжовен език в контекста на славянската микролингвистика (История, динамика на формата и езикови политики)",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Университетско издателство „Неофит Рилски“",
    "place": "Благоевград",
    "isbn": "978-954-00-0262-0",
    "doi": "",
    "url": "",
    "abstract": "Книгата представя историята на книжовния език на българите католици, живеещи в мултиетничната област Банат – от кодифицирането му през 1866 г. – до наши дни. Основната част на изследването е свързана с ревитализацията на книжовните традиции на тази общност след 1990 година. Акцентът е върху динамиката на лексикалната му система, предизвикана от новите обществено-политически и икономически условия. Представени са различни визии за модернизацията му, както и някои опити за (ре)кодификация на нормативната система.",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "2BTY9XMN",
    "type": "Книга",
    "year": 2022,
    "authors": [
      "Петков, Петко"
    ],
    "editors": [],
    "translators": [],
    "title": "Zaropismo illi Balgarska istoria на отец Едоардо Валпа от 1849 г.",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Буквица",
    "place": "София",
    "isbn": "978-954-92858-7-1",
    "doi": "",
    "url": "",
    "abstract": "Книгата представлява филологическо изследване и издание на павликянската българска история от 1849, дело на отец Едоардо Валпа. Това е първо пълно издание на паметник на павликянската книжнина. Изданието е критическо, с включен материал от всички налични ръкописи. Паралелно се издава и текста на Царственника от 1844. Съдържа и езиково описание.",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "LB2I8D5E",
    "type": "Глава от книга",
    "year": 2022,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [
      "Коева, Светла"
    ],
    "translators": [],
    "title": "Новооткрит ръкопис на отец Едуардо осветява обществените отношения сред българите католици през XIX вeк",
    "translatedTitle": "",
    "container": "Доклади от Международната годишна конференция на Института за български език „Проф. Любомир Андрейчин“",
    "volume": "",
    "issue": "",
    "pages": "338–341",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "The report is dedicated to a newly discovered manuscript from the 19th century in Rakovski, written by Father Eduardo of Torino and represents a notarial book in which agreements and wills of Bulgarian Catholics are recorded. The manuscript belongs to the literature of Bulgarian Catholics, is not known to scientists and the next report presents for the first time data on its content and features. The discovery enriches the idea of this part of Bulgarian literature, as this type of notarial book has not been discovered, described and researched so far, and it contains valuable information about public relations between the representatives of this part of the Bulgarian people. The manuscript adds important data to the knowledge of the work of Father Eduardo of Torino, who wrote in modern Bulgarian language among Bulgarian Catholics in the second half of the 19th century.",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "HDTTHJ6I",
    "type": "Статия",
    "year": 2023,
    "authors": [
      "Брага, Татяна"
    ],
    "editors": [],
    "translators": [],
    "title": "Диахронен аспект на българската антропонимна система през XIX в. Езикови особености. Тенденции",
    "translatedTitle": "Diachronic Aspects of the Bulgarian Anthroponymic System in the 19th Century: Linguistic Features and Trends",
    "container": "Български език",
    "volume": "70",
    "issue": "3",
    "pages": "45–63",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "10.47810/BL.70.23.03.04",
    "url": "",
    "abstract": "The article presents results of a study of the historical aspects of Bulgarian anthro-ponymy obtained as part of a postdoctoral project. The study is based on 19th-century archival materials that have been introduced into scientific circulation only recently. It reveals the unique features of the formation of the anthroponymy char-acteristic of a Bulgarian community outside Bulgaria’s ethnic territory. The study presents linguistic and statistical data on 19th-century Bulgarian personal names, highlighting the changes in the personal name system of the settlers in Tabak (South Bessarabia) that took place under polylinguistic influence.",
    "tags": [
      "Bessarabian Bulgarians",
      "historical anthroponymy",
      "personal names",
      "бесарабски българи",
      "историческа антропонимия",
      "лични имена"
    ],
    "topic": "Бесарабия",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "2HB33244",
    "type": "Глава от книга",
    "year": 2023,
    "authors": [
      "Брага, Татяна"
    ],
    "editors": [],
    "translators": [],
    "title": "Из историята и антропонимията на едно българско село в Южна Бесарабия",
    "translatedTitle": "On the history and anthroponymy of a Bulgarian village in Southern Bessarabia",
    "container": "Доклади от Международната годишна конференция на Института за български език „Проф. Любомир Андрейчин“ (София, 2023 година)",
    "volume": "",
    "issue": "",
    "pages": "228–239",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "The diachronic aspect of Bulgarian anthroponymy and the problems related to the language, history and cultural heritage of Bulgarian communities outside the state borders have never lost their relevance for Bulgarian science. The focus of this study is a little-studied aspect of the problems related to the personal name system of the Bulgarian immigrants from Southern Bessarabia. The purpose of the article is to systematize and introduce into scientific circulation anthroponymic data from archival documents from the beginning of the 19th century. The article presents the discussion about the name of the village, as well as various hypotheses about the origin of the oikonym and the toponymic space (residential district names).",
    "tags": [
      "Bessarabian Bulgarians",
      "Bulgarian onomastics",
      "historical anthroponymy",
      "personal names",
      "бесарабски българи",
      "българска ономастика",
      "историческа антропонимия",
      "лични имена"
    ],
    "topic": "Бесарабия",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "C89QIESM",
    "type": "Глава от книга",
    "year": 2023,
    "authors": [
      "Braga, T."
    ],
    "editors": [],
    "translators": [],
    "title": "Personal and Family Names of the Bessarabian Bulgarians of the 19th Century in Sociolinguistic and Cultural-Historical Context",
    "translatedTitle": "",
    "container": "Disciplina Variabilis: Proceedings of the Fourth Annual Doctoral Readings of the Department of Culture, Historical Heritage and Tourism, University of Library Studies and Information Technologies (Sofia, 16–17 November 2023)",
    "volume": "",
    "issue": "",
    "pages": "271–294",
    "publisher": "Za Bukvite – O Pismeneh Academic Publishing House",
    "place": "Sofia",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Бесарабия",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "BMFSKHMT",
    "type": "Статия",
    "year": 2023,
    "authors": [
      "Абаджиева, Магдалена",
      "Цибранска-Костова, Марияна"
    ],
    "editors": [],
    "translators": [],
    "title": "Книжнината на българите католици в христоматия: предизвикателства на лингводидактиката и културологията",
    "translatedTitle": "",
    "container": "Чуждоезиково обучение",
    "volume": "50",
    "issue": "3",
    "pages": "294–304",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "10.53656/for23.331knij",
    "url": "https://journals.azbuki.bg/en/foreignlanguages/knizninata-na-blgarite-katolici-v-xristomatiya-predizvikatelstva-na-lingvodidaktikata-i-kulturologiyata/view",
    "abstract": "The article outlines the scope and methodological principles for the compilation of a Chrestomathy with samples of the literature of the Bulgarian Catholics in the period XVII – XXI centuries. Its significant representatives from diachrony to synchrony are summarized. The project of the Chrestomathy aims at delineating the cultural identity of the marginal group of Banat Bulgarians as part of a much larger and long-standing tradition. Such a product of linguodidactics and literary history would be useful not only for Bulgarian studies, but also for the typological study of foreign linguistic and literary influences on the Bulgarian Catholic community in Bulgaria and abroad, for the interlanguage contacts of Bulgarian with Latin, Italian, Croatian, Romanian, Hungarian language.",
    "tags": [
      "Banat",
      "Banat Bulgarians",
      "foreign linguistic influences on the Bulgarian language",
      "literature of Bulgarian Catholics"
    ],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "AB8D5EKV",
    "type": "Книга",
    "year": 2023,
    "authors": [
      "Цибранска-Костова, Марияна"
    ],
    "editors": [],
    "translators": [],
    "title": "Абагар на Филип Станиславов от 1651 г. Наборен текст. Новобългарски превод. Речник",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "LQM5A3FY",
    "type": "Статия",
    "year": 2023,
    "authors": [
      "Караджова, Даринка"
    ],
    "editors": [],
    "translators": [],
    "title": "Отец Марко от Чипровци – дървото на познанието и философията на устояването",
    "translatedTitle": "",
    "container": "Лингвистични проблеми",
    "volume": "3",
    "issue": "3",
    "pages": "89–95",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Българи католици",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "EQ6SLPIZ",
    "type": "Глава от книга",
    "year": 2023,
    "authors": [
      "Антонова-Василева, Лучия"
    ],
    "editors": [
      "Александрова, Татяна"
    ],
    "translators": [],
    "title": "Учебната книжнина на банатските българи – вековна традиция и съвременни проблеми",
    "translatedTitle": "",
    "container": "Да попитаме Владко Мурдаров. Текстове, посветени на 75-годишнината на езиковеда и преводача проф. д.ф.н. Владко Мурдаров",
    "volume": "",
    "issue": "",
    "pages": "421–433",
    "publisher": "Академично издателство „Проф. Марин Дринов“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "8ZULX6D2",
    "type": "Книга",
    "year": 2024,
    "authors": [
      "Абаджиева, Магдалена"
    ],
    "editors": [],
    "translators": [],
    "title": "Книжнината на българите католици от XIX век и банатската книжнина",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Издателство на БАН „Проф. Марин Дринов“",
    "place": "София",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Банат",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "59LVGD8X",
    "type": "Статия",
    "year": 2025,
    "authors": [
      "Брага, Татяна"
    ],
    "editors": [],
    "translators": [],
    "title": "Именната периферия в Болградско: редки женски антропоними сред бесарабските българи през XIX век и днес",
    "translatedTitle": "The Onomastic Periphery of the Bolhrad Region: Rare Female Anthroponyms among the Bessarabian Bulgarians in the 19th Century and Today",
    "container": "Ѕѣло",
    "volume": "13",
    "issue": "32",
    "pages": "",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "This study examines female personal names attested among the Bessarabian Bulgarians of Bolhrad (Odesa region, Ukraine), descendants of Bulgarian populations who left their native lands in the early nineteenth century and settled in Southern Bessarabia. The analysis is based on archival documents collected through targeted fieldwork and archival research. Particular attention is paid to rarely attested and distinctive female names that illustrate processes of introduction, persistence, and disappearance within the anthroponymic system of the Bessarabian Bulgarians. Many of these names are absent from later historical sources, which makes them a unique resource for Bulgarian historical onomastics. At the same time, they function as carriers of ancestral and national memory within the Bessarabian Bulgarian community. The article also traces the trajectories of selected common and rare names in the contemporary female naming repertoire, drawing on data from the 2001 population census to examine their present-day distribution.",
    "tags": [
      "19 век",
      "20 век",
      "Bessarabian Bulgarians",
      "Bolhrad",
      "female personal names",
      "historical anthroponymy",
      "personal names",
      "Болград",
      "бесарабски българи",
      "женски лични имена",
      "историческа антропонимия",
      "лични имена"
    ],
    "topic": "Бесарабия",
    "places": [
      "Болград"
    ],
    "kind": "Изследване"
  },
  {
    "id": "56SFNTXH",
    "type": "Книга",
    "year": 2025,
    "authors": [
      "Braga, Tatyana"
    ],
    "editors": [],
    "translators": [],
    "title": "The Names of the Bulgarians in the Bolgrad Region (Southern Bessarabia), Part I: The Identity of the Bessarabian Bulgarians Between Language, History, and Migration",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "",
    "place": "",
    "isbn": "978-619-245-558-3",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Бесарабия",
    "places": [
      "Болград"
    ],
    "kind": "Изследване"
  },
  {
    "id": "7Q5ZFNGI",
    "type": "Книга",
    "year": 2025,
    "authors": [],
    "editors": [
      "Moşin, Octavian",
      "Gumenâi, Ion"
    ],
    "translators": [],
    "title": "Biserica ortodoxă și implicațiile sale în procesele educativ-culturale din spațiul românesc în secolul al XIX-lea – secolul al XXI-lea",
    "translatedTitle": "",
    "container": "",
    "volume": "",
    "issue": "",
    "pages": "",
    "publisher": "Lexon-Prim",
    "place": "Chișinău",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "",
    "tags": [],
    "topic": "Бесарабия",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "I7HLZ7AM",
    "type": "Глава от книга",
    "year": 2025,
    "authors": [
      "Думиника, Иван"
    ],
    "editors": [
      "Moşin, Octavian",
      "Gumenâi, Ion"
    ],
    "translators": [],
    "title": "Варзоповы – династия болгарских священнослужителей Бессарабии (1834–1939)",
    "translatedTitle": "",
    "container": "Biserica ortodoxă și implicațiile sale în procesele educativ-culturale din spațiul românesc în secolul al XIX-lea – secolul al XXI-lea",
    "volume": "",
    "issue": "",
    "pages": "149–160",
    "publisher": "Lexon-Prim",
    "place": "Chișinău",
    "isbn": "",
    "doi": "",
    "url": "https://www.researchgate.net/publication/412213308_BISERICA_ORTODOXA_SI_IMPLICATIILE_SALE_IN_PROCESELE_EDUCATIV-CULTURALE_DIN_SPATIUL_ROMANESC_in_secolul_al_XIX-lea_-_secolul_al_XXI-lea",
    "abstract": "",
    "tags": [],
    "topic": "Бесарабия",
    "places": [],
    "kind": "Изследване"
  },
  {
    "id": "ZRPT7STU",
    "type": "Статия",
    "year": 2026,
    "authors": [
      "Брага, Татяна"
    ],
    "editors": [],
    "translators": [],
    "title": "Рядко засвидетелствани мъжки лични имена в антропонимикона на бесарабските българи от Болградско през XIX век",
    "translatedTitle": "Rarely attested male personal names in the anthroponymic system of the Bessarabian Bulgarians from the Bolhrad region in the 19th century",
    "container": "Ѕѣло",
    "volume": "14",
    "issue": "33",
    "pages": "",
    "publisher": "",
    "place": "",
    "isbn": "",
    "doi": "",
    "url": "",
    "abstract": "The article examines male personal names of the Bessarabian Bulgarians in the nineteenth century, with a focus on rarely attested and specific anthroponyms. These names are of high indicative value, as they reflect processes of inclusion and disappearance within the naming system. A significant number of them do not appear in later historical sources, which makes them a valuable object of study in Bulgarian historical onomastics. Their predominantly native origin testifies to the stability of the Bulgarian linguistic and cultural tradition. By correlating anthroponymic data with historical and sociocultural context, the study reveals the mechanisms by which naming traditions are preserved and transmitted as carriers of familial and national memory within the Bessarabian Bulgarian diaspora",
    "tags": [
      "19 век",
      "Bessarabian Bulgarians",
      "cultural identity",
      "diaspora",
      "historical onomastics",
      "male personal names",
      "бесарабски българи",
      "диаспора",
      "историческа ономастика",
      "културна идентичност",
      "лични имена",
      "мъжки лични имена"
    ],
    "topic": "Бесарабия",
    "places": [
      "Болград"
    ],
    "kind": "Изследване"
  }
];
